allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular/common@21.2.15'
  - '@angular/compiler-cli@21.2.15'
  - '@angular/compiler@21.2.15'
  - '@angular/core@21.2.15'
  - '@angular/forms@21.2.15'
  - '@angular/localize@21.2.15'
  - '@angular/platform-browser@21.2.15'
  - '@angular/router@21.2.15'
