allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular/common@21.2.15'
  - '@angular/compiler-cli@21.2.15'
  - '@angular/compiler@21.2.15'
  - '@angular/core@21.2.15'
  - '@angular/forms@21.2.15'
  - '@angular/localize@21.2.15'
  - '@angular/platform-browser@21.2.15'
  - '@angular/router@21.2.15'
  - '@myrmidon/auth-jwt-admin@9.0.0'
  - '@myrmidon/auth-jwt-login@9.0.0'
  - '@myrmidon/cadmus-refs-lookup@11.0.0'
  - '@myrmidon/ngx-mat-tools@2.0.0'
  - '@myrmidon/ngx-tools@3.0.0'
  - '@myrmidon/paged-data-browsers@6.0.0'
  - '@angular-devkit/architect@0.2200.1'
  - '@angular-devkit/core@22.0.1'
  - '@angular-devkit/schematics@22.0.1'
  - '@angular/cli@22.0.1'
  - '@schematics/angular@22.0.1'
  - '@angular/build@22.0.1'
  - '@angular/cdk@22.0.1'
  - '@angular/common@22.0.1'
  - '@angular/compiler-cli@22.0.1'
  - '@angular/compiler@22.0.1'
  - '@angular/core@22.0.1'
  - '@angular/forms@22.0.1'
  - '@angular/localize@22.0.1'
  - '@angular/material@22.0.1'
  - '@angular/platform-browser@22.0.1'
  - '@angular/router@22.0.1'
